### ISSUE TITLE
Create an Issue Practice

### ISSUE THREAD

**Issue by sagehrke** [nicolevasilevsky/c-path-practice#3]
Practicing creating an issue in GitHub by following the [GitHub Issue for OBO Engineers](https://oboacademy.github.io/obook/tutorial/github-issues/#create-issues) tutorial. 
- [ ] steps to a real issue would go here. 
- [ ] another step. 
- [ ] and one more.

**Comment by sagehrke** [comment]
@nicolevasilevsky while not a huge deal for me in this moment as I have done other GitHub tutorials, my access level for this repo is not allowing me to do the tasks listed in the tutorial including:
- assigning the ticket to someone
- adding a label
- creating a new label and adding it to the ticket

![8-on-sofa-6 5-looking - 1](https://user-images.githubusercontent.com/99770056/165638704-413faa7f-4f6b-4ebe-998f-714b0ceb1110.png)

Including this picture of kittens, because we need more kittens in our lives. Reference #1

**Comment by sagehrke** [comment]
@nicolevasilevsky I also don't see options to play with making a new project or milestone as the [tutorial](https://oboacademy.github.io/obook/tutorial/github-issues/) suggests.

**Comment by nicolevasilevsky** [comment]
This is a great kitten picture!

I'll give you access

**Comment by nicolevasilevsky** [comment]
I sent you an invitation

**Comment by sagehrke** [comment]
training tutorial complete.
